# Generated by Django 6.0.3 on 2026-04-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_hidden'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_listings',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='listings.listing'),
        ),
    ]
