# Generated by Django 6.0.3 on 2026-05-09 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_picture_user_uploadcare_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='savedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('saved_url', models.CharField(max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_search', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
