# Generated by Django 6.0.3 on 2026-05-12 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_city_province_user_city_city_province_user_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.province'),
        ),
    ]
