# Generated by Django 6.0.3 on 2026-05-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_listing_view_count'),
        ('users', '0011_rename_user_uploadcare_uuid_to_storage_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite_listings',
            field=models.ManyToManyField(blank=True, related_name='favourited_by', to='listings.listing'),
        ),
    ]
