# Generated by Django 6.0.3 on 2026-05-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_created_at_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_code_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
