# Generated by Django 6.0.3 on 2026-05-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_email_verification_code_and_more'),
    ]

    # No-op: field type was correct in 0014. Kept so migration numbering stays intact.
    operations = []
