# Generated by Django 6.0.3 on 2026-05-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_email_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
