# Generated by Django 6.0.3 on 2026-05-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_email_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_recovery_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_recovery_code_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
