# Generated by Django 6.0.3 on 2026-05-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_password_recovery_code_and_more'),
    ]

    # No-op: field type was corrected in 0016. Kept so migration numbering stays intact.
    operations = []
