# Generated by Django 6.0.3 on 2026-05-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_password_recovery_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_recovery_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
