# Generated by Django 6.0.3 on 2026-06-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_company_name_alter_user_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_private',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
