# Generated by Django 6.0.3 on 2026-04-25 20:54

import django.db.models.deletion
import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('makeyear', models.DateField()),
                ('price', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('power', models.IntegerField()),
                ('is_online', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.carbodytype')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.carbrand')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.carcondition')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.carfueltype')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.carmodel')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.cartransmissiontype')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=listings.models.listing_image_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
        ),
    ]
