# Generated by Django 6.0.3 on 2026-04-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
