# Generated by Django 6.0.3 on 2026-05-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='old_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
    ]
