# Generated by Django 6.0.1 on 2026-03-17 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_rename_body_type_carbodytype_name_and_more'),
        ('listings', '0004_alter_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='body_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carbodytype'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carbrand'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carcondition'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='fuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carfueltype'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carmodel'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='transmission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cartransmissiontype'),
        ),
    ]
