# Generated by Django 6.0.1 on 2026-03-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_body_type_alter_listing_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='makeyear',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='mileage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='power',
            field=models.IntegerField(null=True),
        ),
    ]
