# Generated by Django 6.0.3 on 2026-05-06 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_city_province_listing_description_listing_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.TextField(blank=True, default='title', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connected_cities', to='listings.province'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.city'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.province'),
        ),
    ]
