# Generated by Django 6.0.1 on 2026-03-17 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_rename_body_type_carbodytype_name_and_more'),
        ('listings', '0006_alter_listing_makeyear_alter_listing_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='body_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.carbodytype'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.carbrand'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.carcondition'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.carfueltype'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='makeyear',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='mileage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.carmodel'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='power',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.cartransmissiontype'),
        ),
    ]
