# Generated by Django 6.0.3 on 2026-05-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_title_alter_city_province_alter_listing_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.TextField(max_length=2000),
        ),
    ]
