# Generated by Django 6.0.3 on 2026-05-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_listing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uploadcare_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
