# Generated by Django 6.0.1 on 2026-03-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
