# Generated by Django 6.0.1 on 2026-03-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_online',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='publish_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
