# Generated by Django 6.0.3 on 2026-05-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_image_uploadcare_uuid_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
