# Generated by Django 6.0.1 on 2026-03-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_listing_is_online_alter_listing_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
