# Generated by Django 6.0.3 on 2026-05-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_pricehistory_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='city',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='province',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
