# Generated by Django 6.0.3 on 2026-05-15 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_carmodel_connected_brand_carmodeltrim'),
        ('listings', '0014_remove_listing_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='model_trim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.carmodeltrim'),
        ),
    ]
