# Generated by Django 6.0.3 on 2026-05-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_listing_ranges_garantie_pickerl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='battery_size',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='drivetrain',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='factory_range',
        ),
    ]
