# Generated by Django 6.0.3 on 2026-05-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_remove_listing_battery_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_under_edit',
            field=models.BooleanField(default=True),
        ),
    ]
