# Generated by Django 6.0.3 on 2026-05-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_listing_is_under_edit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='hidden',
            new_name='deactivated',
        ),
    ]
