# Generated by Django 6.0.3 on 2026-05-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_rename_hidden_listing_deactivated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='deactivated',
        ),
        migrations.AddField(
            model_name='listing',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
