# Generated by Django 6.0.3 on 2026-05-16 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_remove_listing_deactivated_listing_is_reserved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_under_edit',
            new_name='is_under_review',
        ),
    ]
