# Generated by Django 6.0.3 on 2026-05-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_rename_is_under_edit_listing_is_under_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='heat_pump',
            field=models.BooleanField(default=True),
        ),
    ]
