# Generated by Django 6.0.3 on 2026-05-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_rename_image_uploadcare_uuid_to_storage_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
