# Generated by Django 6.0.3 on 2026-05-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_listing_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
    ]
