# Generated by Django 6.0.3 on 2026-06-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_listingreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='battery_health',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
