# Generated by Django 6.0.3 on 2026-08-23 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_delete_carfueltype_delete_cartransmissiontype'),
        ('listings', '0029_listing_battery_health'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('battery_health__isnull', True), models.Q(('battery_health__gte', 0), ('battery_health__lte', 100)), _connector='OR'), name='battery_health_validator', violation_error_message='Battery health needs to be between 0 and 100'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0), ('mileage__gte', 1), ('power__gte', 1), models.Q(('real_summer_range__isnull', True), ('real_summer_range__gte', 1), _connector='OR'), models.Q(('real_winter_range__isnull', True), ('real_winter_range__gte', 1), _connector='OR')), name='integer_values_validator', violation_error_message='Integer values must be within their allowed ranges'),
        ),
    ]
