# Generated by Django 6.0.3 on 2026-08-23 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_delete_carfueltype_delete_cartransmissiontype'),
        ('listings', '0030_listing_battery_health_validator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listing',
            name='integer_values_validator',
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0), ('mileage__gte', 1), ('power__gte', 1), ('view_count__gte', 0), models.Q(('real_summer_range__isnull', True), ('real_summer_range__gte', 1), _connector='OR'), models.Q(('real_winter_range__isnull', True), ('real_winter_range__gte', 1), _connector='OR')), name='integer_values_validator', violation_error_message='Integer values must be within their allowed ranges'),
        ),
    ]
