# Generated by Django 6.0.3 on 2026-05-15 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_delete_cartransmissiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='connected_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='cars.carbrand'),
        ),
        migrations.CreateModel(
            name='CarModelTrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('connected_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trims', to='cars.carmodel')),
            ],
        ),
    ]
