# Generated by Django 6.0.3 on 2026-03-15 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_brand_remove_car_model_carmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carbrand'),
        ),
    ]
