# Generated by Django 6.0.1 on 2026-03-17 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_car_car_model_remove_carmodel_brand_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='connected_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carbrand'),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
