# Generated by Django 6.0.3 on 2026-05-16 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_carmodeltrim_charging_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodeltrim',
            name='battery_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodeltrim',
            name='drivetrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.cardrivetrain'),
        ),
        migrations.AddField(
            model_name='carmodeltrim',
            name='factory_range',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
