# Generated by Django 6.0.1 on 2026-03-17 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_carmodel_connected_brand_delete_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbodytype',
            old_name='body_type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='carbrand',
            old_name='brand',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='carcondition',
            old_name='condition',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='carfueltype',
            old_name='fuel_type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='model',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cartransmissiontype',
            old_name='transmission_type',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='connected_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='cars.carbrand'),
        ),
    ]
