# Generated by Django 6.0.3 on 2026-05-28 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_carmodeltrim_battery_size_carmodeltrim_drivetrain_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS cars_carfueltype CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS cars_cartransmissiontype CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='CarFuelType',
                ),
                migrations.DeleteModel(
                    name='CarTransmissionType',
                ),
            ],
        ),
    ]
